// Package integrate installs Specula as an additive client-side mirror for
// supported package ecosystems without destroying the operator's existing
// configuration (prepend / append / side-file only).
package integrate

import (
	"encoding/json"
	"fmt"
	"net/url"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// DefaultProtocols is the set applied when --protocols is omitted.
var DefaultProtocols = []string{"go", "npm", "pypi", "oci", "helm", "git", "apt"}

// Options configures an integrate run.
type Options struct {
	// Addr is the Specula data-plane base URL, e.g. http://127.0.0.1:7732
	Addr string
	// Protocols is the list of protocol names to wire (go, npm, pypi, oci, helm, git, apt).
	Protocols []string
	// DryRun reports planned changes without writing.
	DryRun bool
	// Home overrides the user home directory (tests).
	Home string
	// SkipRoot skips actions that require root (apt sources, /etc/docker).
	// When false, those actions still attempt and report permission errors.
	SkipRoot bool
}

// Result is one protocol's integrate outcome.
type Result struct {
	Protocol string `json:"protocol"`
	Action   string `json:"action"` // added | already | skipped | error
	Detail   string `json:"detail"`
	Path     string `json:"path,omitempty"`
	Err      string `json:"error,omitempty"`
}

// Report is the full integrate run summary.
type Report struct {
	Addr    string   `json:"addr"`
	DryRun  bool     `json:"dry_run"`
	Results []Result `json:"results"`
}

// Run applies additive client wiring for the requested protocols.
func Run(opts Options) (Report, error) {
	addr, err := normalizeAddr(opts.Addr)
	if err != nil {
		return Report{}, err
	}
	home := opts.Home
	if home == "" {
		home, err = os.UserHomeDir()
		if err != nil {
			return Report{}, fmt.Errorf("home dir: %w", err)
		}
	}
	protos := opts.Protocols
	if len(protos) == 0 {
		protos = append([]string(nil), DefaultProtocols...)
	}

	rep := Report{Addr: addr, DryRun: opts.DryRun}
	for _, p := range protos {
		p = strings.ToLower(strings.TrimSpace(p))
		var r Result
		switch p {
		case "go", "gomod":
			r = integrateGo(home, addr, opts.DryRun)
			r.Protocol = "go"
		case "npm":
			r = integrateNPM(home, addr, opts.DryRun)
		case "pypi", "pip":
			r = integratePip(home, addr, opts.DryRun)
			r.Protocol = "pypi"
		case "oci", "docker":
			r = integrateDocker(home, addr, opts.DryRun, opts.SkipRoot)
			r.Protocol = "oci"
		case "helm":
			r = integrateHelm(addr, opts.DryRun)
		case "git":
			r = integrateGit(home, addr, opts.DryRun)
		case "apt":
			r = integrateApt(addr, opts.DryRun, opts.SkipRoot)
		case "tarball":
			r = Result{Protocol: "tarball", Action: "skipped", Detail: "tarball has no global client config; use Specula URLs directly"}
		default:
			r = Result{Protocol: p, Action: "error", Err: "unknown protocol"}
		}
		if r.Protocol == "" {
			r.Protocol = p
		}
		rep.Results = append(rep.Results, r)
	}

	if !opts.DryRun {
		_ = writeState(home, rep)
		_ = writeEnvFile(home, addr, rep)
	}
	return rep, nil
}

// Status reads the last integrate state file, if any.
func Status(home string) (Report, error) {
	if home == "" {
		var err error
		home, err = os.UserHomeDir()
		if err != nil {
			return Report{}, err
		}
	}
	b, err := os.ReadFile(statePath(home))
	if err != nil {
		if os.IsNotExist(err) {
			return Report{}, fmt.Errorf("no integrate state yet — run: specula integrate")
		}
		return Report{}, err
	}
	var rep Report
	if err := json.Unmarshal(b, &rep); err != nil {
		return Report{}, err
	}
	return rep, nil
}

func normalizeAddr(addr string) (string, error) {
	addr = strings.TrimSpace(addr)
	if addr == "" {
		addr = "http://127.0.0.1:7732"
	}
	u, err := url.Parse(addr)
	if err != nil || u.Scheme == "" || u.Host == "" {
		return "", fmt.Errorf("invalid --addr %q (want http://host:port)", addr)
	}
	u.Path = strings.TrimRight(u.Path, "/")
	return u.String(), nil
}

func statePath(home string) string {
	return filepath.Join(home, ".config", "specula", "integrate-state.json")
}

func envPath(home string) string {
	return filepath.Join(home, ".config", "specula", "env.sh")
}

func writeState(home string, rep Report) error {
	dir := filepath.Dir(statePath(home))
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	b, err := json.MarshalIndent(rep, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(statePath(home), b, 0o644)
}

func writeEnvFile(home, addr string, rep Report) error {
	var b strings.Builder
	b.WriteString("# Generated by `specula integrate` — safe to source from your shell rc.\n")
	b.WriteString("# Additive helpers; tool-native configs (go env, npmrc, …) are authoritative.\n")
	b.WriteString("export SPECULA_ADDR=" + shellQuote(addr) + "\n")
	// Ensure clients reach Specula DIRECTLY. Ambient HTTP_PROXY/HTTPS_PROXY
	// (Clash, corporate MITM, …) would otherwise intercept 127.0.0.1:7732 or a
	// remote Specula host and you cannot tell whether bytes came from Specula.
	host := hostOfAddr(addr)
	if host != "" {
		b.WriteString("# Bypass ambient HTTP proxies for Specula itself (additive).\n")
		b.WriteString("export NO_PROXY=\"${NO_PROXY:+$NO_PROXY,}" + host + ",127.0.0.1,localhost\"\n")
		b.WriteString("export no_proxy=\"${no_proxy:+$no_proxy,}" + host + ",127.0.0.1,localhost\"\n")
	}
	for _, r := range rep.Results {
		if r.Action == "error" {
			continue
		}
		switch r.Protocol {
		case "go":
			b.WriteString("# GOPROXY is managed via: go env -w GOPROXY=...\n")
		case "pypi":
			b.WriteString("# PIP_INDEX_URL is also in pip.conf; optional session override:\n")
			b.WriteString("# export PIP_INDEX_URL=" + shellQuote(addr+"/pypi/simple") + "\n")
		}
	}
	dir := filepath.Dir(envPath(home))
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	return os.WriteFile(envPath(home), []byte(b.String()), 0o644)
}

// hostOfAddr returns the host (no port) from an http(s) base URL.
func hostOfAddr(addr string) string {
	addr = strings.TrimSpace(addr)
	u, err := url.Parse(addr)
	if err != nil || u.Host == "" {
		// Fallback: strip scheme manually.
		addr = strings.TrimPrefix(addr, "http://")
		addr = strings.TrimPrefix(addr, "https://")
		host, _, _ := strings.Cut(addr, "/")
		host, _, _ = strings.Cut(host, ":")
		return host
	}
	return u.Hostname()
}

func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

// PrintReport writes a human-readable summary to w.
func PrintReport(rep Report) string {
	var b strings.Builder
	fmt.Fprintf(&b, "specula integrate  addr=%s", rep.Addr)
	if rep.DryRun {
		b.WriteString("  (dry-run)")
	}
	b.WriteByte('\n')
	sort.SliceStable(rep.Results, func(i, j int) bool {
		return rep.Results[i].Protocol < rep.Results[j].Protocol
	})
	for _, r := range rep.Results {
		switch r.Action {
		case "error":
			fmt.Fprintf(&b, "  ✗ %-6s  %s\n", r.Protocol, r.Err)
		case "skipped":
			fmt.Fprintf(&b, "  · %-6s  %s\n", r.Protocol, r.Detail)
		case "already":
			fmt.Fprintf(&b, "  ✓ %-6s  already configured — %s\n", r.Protocol, r.Detail)
		default:
			fmt.Fprintf(&b, "  ✓ %-6s  %s", r.Protocol, r.Action)
			if r.Detail != "" {
				fmt.Fprintf(&b, " — %s", r.Detail)
			}
			if r.Path != "" {
				fmt.Fprintf(&b, " (%s)", r.Path)
			}
			b.WriteByte('\n')
		}
	}
	return b.String()
}
